# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 14:22
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='ano',
            field=models.PositiveIntegerField(default=2017),
        ),
        migrations.AddField(
            model_name='ficha',
            name='coorientador',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='curso',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='cutter',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AddField(
            model_name='ficha',
            name='fonte',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times', 'Times')], default='Arial', max_length=5),
        ),
        migrations.AddField(
            model_name='ficha',
            name='orientador',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sobrenome',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='sub_titulo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tamanho_fonte',
            field=models.PositiveIntegerField(default=12, validators=[django.core.validators.MaxValueValidator(42), django.core.validators.MinValueValidator(4)]),
        ),
        migrations.AddField(
            model_name='ficha',
            name='tipo_trabalho',
            field=models.CharField(choices=[('Monografia', 'Monografia'), ('Dissertação', 'Dissertação'), ('Tese', 'Tese')], default='Monografia', max_length=12),
        ),
        migrations.AddField(
            model_name='ficha',
            name='titulo',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='nome',
            field=models.CharField(default='', max_length=50),
        ),
    ]
