# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 11:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0003_auto_20170324_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fonte',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times New Roman', 'Times')], default='Arial', max_length=15),
        ),
    ]
