# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0005_auto_20170324_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fonte',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times', 'Times New Roman'), ('Monospace', 'Monoespaçada')], default='Arial', max_length=15),
        ),
    ]
