# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0007_auto_20170503_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='titulo_obtido',
            field=models.CharField(choices=[('Bacharelado', 'Bacharelado'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], default='Bacharelado', max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto1',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto2',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto3',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto4',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto5',
            field=models.CharField(default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sub_titulo',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
