# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-17 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0008_auto_20170517_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='assunto1',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto2',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto3',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto4',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='assunto5',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='sub_titulo',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
