# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0010_ficha_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='cidade',
            field=models.CharField(default='Palmas', max_length=100),
        ),
    ]
