# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 14:55
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0011_ficha_cidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fonte',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times', 'Times New Roman')], default='Times New Roman', max_length=15),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='tamanho_fonte',
            field=models.PositiveIntegerField(default=11, validators=[django.core.validators.MaxValueValidator(42), django.core.validators.MinValueValidator(4)]),
        ),
    ]
