# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-18 14:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0012_auto_20170518_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='fonte',
            field=models.CharField(choices=[('Arial', 'Arial'), ('Times', 'Times New Roman')], default='Times', max_length=15),
        ),
    ]
