# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-24 01:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0015_auto_20170524_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='assunto1',
            field=models.CharField(blank=True, choices=[('340', 'Direito'), ('341', 'Direito Público'), ('341.1', 'Direito Internacional Público'), ('341.14', 'Direito Penal Internacional'), ('341.2', 'Direito Constitucional'), ('341.27', 'Direitos Fundamentais'), ('341.28', 'Direito Eleitoral'), ('341.3', 'Direito Administrativo'), ('341.347', 'Direito Ambiental'), ('341.378', 'Direito Econômico'), ('341.38', 'Direito Financeiro'), ('341.39', 'Direito Tributário'), ('341.4', 'Direito Processual'), ('341.43', 'Direito Processual Penal'), ('341.46', 'Direito Processual Civil'), ('341.5', 'Direito Penal'), ('341.58', 'Direito Penitenciário. Direito de Execuções Penais'), ('341.6', 'Direito Previdenciário. Seguridade Social'), ('341.7', 'Direito Militar'), ('341.75', 'Direito Penal Militar'), ('341.8', 'Direito Aéreo. Código do Ar'), ('341.87', 'Direito Aéreo Militar'), ('341.88', 'Direito aplicado à Telecomunicação'), ('341.89', 'Direito Espacial'), ('342', 'Direito Privado'), ('342.1', 'Direito Civil'), ('342.12', 'Direitos Reais, Coisas e Bens'), ('342.16', 'Direito de Família'), ('342.165', 'Direito das Sucessões'), ('342.17', 'Direito do Menor.'), ('342.2', 'Direito Comercial'), ('342.234', 'Direito Bancário'), ('342.27', 'Direitos Intelectuais. Propriedade industrial, comercial, científica e de programas de computador.'), ('342.28', 'Direito autoral. Direito Artístico e Literário.'), ('342.29', 'Direito Marítimo'), ('342.299', 'Direito Aeronáutico'), ('342.3', 'Direito Internacional Privado'), ('342.5', 'Direito do Consumidor'), ('342.6', 'Direito do Trabalho'), ('342.68', 'Direito Processual do Trabalho')], default='Direito', max_length=25, null=True),
        ),
    ]
