# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0019_auto_20170528_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='anexos',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ficha',
            name='encardenacao',
            field=models.CharField(choices=[('Brochura', 'Brochura'), ('Espiral', 'Espiral')], default='Brochura', max_length=20),
        ),
        migrations.AddField(
            model_name='ficha',
            name='referencias',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
