# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 18:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0020_auto_20170529_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='titulo_obtido',
            field=models.CharField(choices=[('Bacharel', 'Bacharel'), ('Mestre', 'Mestre'), ('Doutor', 'Doutor')], default='Bacharelado', max_length=15),
        ),
    ]
