# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-30 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fichas', '0023_auto_20170530_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='curso',
            field=models.CharField(default='Direito', max_length=200),
        ),
    ]
